<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HelixToolkit.SharpDX.Assimp" Version="3.1.2" />
    <PackageReference Include="HelixToolkit.Wpf" Version="3.1.2" />
    <PackageReference Include="HelixToolkit.Wpf.SharpDX" Version="3.1.2" />
    <PackageReference Include="SharpDX.DirectInput" Version="4.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tiger\Tiger.csproj" />
  </ItemGroup>

</Project>
